# Generated by Django 6.0.1 on 2026-01-22 03:10

import user_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, validators=[user_app.validators.validate_date_joined]),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[user_app.validators.validate_email_domain]),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[user_app.validators.validate_username]),
        ),
    ]
