# Generated by Django 6.0.1 on 2026-01-22 16:55

import post_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(max_length=1000, validators=[post_app.validators.validate_content_length]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=200, validators=[post_app.validators.validate_empty_title, post_app.validators.validate_title_length]),
        ),
    ]
